type Query {

    #User
    findAllUsers: [User]
    findByUserId(id: ID!): User
    findUserByUsername(username: String!): User
    findUserByUsernameContaining(username: String!): User

    #Address
    findByZipcode(zipcode: String): Address

    #Store
    findStoreByCurrentUser: StoreDTO
    findStoreById (id: ID!): StoreDTO
    findStoreByName (name: String!): StoreDTO
    findAllStoreByNameContaining (name: String!): StoreDTO
    findAllStore: [StoreDTO]

    #Product
    findAllProducts (paginatorInput: PaginatorInput!): ProductPaginator!
    findAllWithinRadiusByLngLat (searchingProductInput: SearchingProductInput!): ProductPaginator!
    findByProductId (id: ID): Product
    findAllMyProducts (paginatorInput: PaginatorInput!): ProductPaginator!
    findAllProductsByOwnerId (id: ID, paginatorInput: PaginatorInput!): ProductPaginator!
    findAllByCategory (searchingProductInput: SearchingProductInput!): ProductPaginator!

    #Category
    findByCategoryId (id: ID): Category
    findAllCategories: [Category]

    #Order
    findAllOrders: [Order]
    findByOrderId (id: ID): Order
}