spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/we-make-it
    username: postgres
    password: 123qwe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    servlet:
      maxQueryDepth: 5
    schema:
      printer:
        enabled: false
jwt:
  secret: MYJWTSECRET
  expiration: 3600000